import { Link } from "react-router-dom";
import { equipment } from "../data/equipment";
import { calculateOwnershipMetrics, calculatePackages, calculatePassportScores, generateBuildStory, publicTimeline } from "../domain/passport";
import { ButtonLink } from "../components/ButtonLink";
import { PageFrame } from "../components/PageFrame";
import { SeoSchema } from "../components/SeoSchema";
import { WindowSticker } from "../components/WindowSticker";
import { EquipmentProjects } from "../components/EquipmentProjects";
import { CanonicalPublicDocuments } from "../components/CanonicalPublicDocuments";

const dateLabel = (value?: string) => value ? new Intl.DateTimeFormat("en-US", { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)) : "Date documented privately";

export function EquipmentDetailPage({ slug }: { slug: string }) {
  const item = equipment.find((entry) => entry.slug === slug)!;
  const related = equipment.find((entry) => entry.slug !== slug)!;
  const packages = calculatePackages(item.upgrades, item.packageRules);
  const scores = calculatePassportScores(item);
  const timeline = publicTimeline(item);
  const metrics = calculateOwnershipMetrics(item);
  const buildStory = generateBuildStory(item, packages);
  const publicOptions = item.factoryOptions.filter(({ publicDisplay }) => publicDisplay);
  const installedUpgrades = item.upgrades.filter(({ status }) => status === "installed");
  const plannedUpgrades = item.upgrades.filter(({ status }) => status !== "installed" && status !== "removed");
  const downloads = item.documents.filter(({ publicDisplay, url }) => publicDisplay && url);
  const isMzigoElectric = item.slug === "sp-mzigo-26";

  return <PageFrame><SeoSchema item={item} />
    <nav className="shell breadcrumbs" aria-label="Breadcrumb"><Link to="/">Equipment</Link><span>/</span><span aria-current="page">Passport {item.fleetId}</span></nav>
    <section className={`detail-hero passport-hero${isMzigoElectric ? " detail-hero--electric" : ""}`}><img src={item.heroImage} alt={`${item.fleetId} ${item.category}`} width="1536" height="1024" /><div className="detail-hero__shade" /><div className="ambient-light" aria-hidden="true" /><div className="shell detail-hero__content"><p className="eyebrow">SmashPro Fleet Equipment Passport</p><h1>{item.identity.model}</h1><p className="detail-name">{item.name}{item.pronunciation ? <small> / {item.pronunciation}</small> : null}</p><p className="detail-slogan">{item.slogan}</p><div className="button-row"><ButtonLink href="#identity">Open Passport</ButtonLink><ButtonLink href="#specifications" variant="outline">Factory Specifications</ButtonLink></div></div></section>

    <section className="passport-strip" id="identity"><div className="shell passport-identity">
      <div><span>Passport ID</span><strong>{item.identity.passportId}</strong></div><div><span>Model</span><strong>{item.identity.model}</strong></div><div><span>Edition</span><strong>{item.identity.edition}</strong></div><div><span>Finish</span><strong>{item.identity.finish ?? "Not published"}</strong></div>
    </div></section>

    <WindowSticker item={item} packages={packages} scores={scores} />

    <EquipmentProjects fleetId={item.fleetId} equipmentName={item.name} capabilityIds={item.capabilityIds} attachmentIds={item.attachmentIds} />

    <section className="build-story"><div className="shell"><p className="eyebrow">Build story</p><blockquote>{buildStory}</blockquote><p>This narrative evolves from verified factory, upgrade, package, and media records.</p></div></section>

    <section className="section shell passport-overview"><div><p className="eyebrow">Equipment identity</p><h2>A living record of the machine.</h2><p className="large-copy">{item.overview}</p><div className="status-panel"><span className="status-light" /><div><small>Current public status</small><strong>{item.statusLabel}</strong></div></div></div><div className="passport-scores">
      <article><span>Documentation Score</span><strong>{scores.documentation}</strong><small>/ 100</small></article><article><span>Maintenance Score</span><strong>{scores.maintenance}</strong><small>/ 100</small></article><article className="valuation"><span>Estimated Fleet Value</span><strong>{item.valuation.status === "current" && item.valuation.amount ? new Intl.NumberFormat("en-US", { style: "currency", currency: item.valuation.currency, maximumFractionDigits: 0 }).format(item.valuation.amount) : "Pending"}</strong><small>{item.valuation.status === "current" ? "Public estimate" : "Awaiting verified valuation inputs"}</small></article>
    </div></section>

    <section className="spec-section" id="specifications"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Factory configuration</p><h2>Complete factory specifications.</h2></div><p>Every confirmed manufacturer value is shown. Fields are additive, so future OEM specifications can be published without redesigning the passport.</p></div><dl className="spec-grid passport-spec-grid">{item.specifications.map((spec) => <div key={spec.label}><dt>{spec.group}<small>{spec.label}</small></dt><dd>{spec.value}</dd></div>)}</dl>{item.factoryFinish ? <div className="factory-finish"><div className="factory-finish__heading"><div><p className="eyebrow">Official manufacturing information</p><h3>Factory Finish</h3></div></div><dl className="spec-grid factory-finish__grid"><div><dt>Paint Color</dt><dd>{item.factoryFinish.paintColor}</dd></div><div><dt>Color Standard</dt><dd>{item.factoryFinish.colorStandard}</dd></div><div><dt>Coating Process</dt><dd>{item.factoryFinish.coatingProcess}</dd></div><div><dt>Factory Cure</dt><dd>{item.factoryFinish.factoryCure}</dd></div></dl><aside className="factory-finish__callout"><span>RAL 6018</span><p>{item.factoryFinish.summary}</p></aside></div> : null}</div></section>

    <section className="section shell passport-section"><div className="section-heading"><div><p className="eyebrow">Factory options</p><h2>Installed before delivery.</h2></div><p>Only options approved for public display appear here. Factory costs remain in the private purchase ledger.</p></div>{publicOptions.length ? <div className="passport-card-grid">{publicOptions.map((option) => <article key={option.id}><span>Factory installed</span><h3>{option.name}</h3><p>{option.description}</p></article>)}</div> : <p className="empty-state">No factory options have been published for this asset.</p>}</section>

    <section className="passport-dark"><div className="section shell passport-section"><div className="section-heading"><div><p className="eyebrow">SmashPro installed upgrades</p><h2>Built beyond factory.</h2></div><p>Install records can link vendors, warranties, images, receipts, and episodes. Financial documents remain private.</p></div>{installedUpgrades.length ? <div className="passport-card-grid">{installedUpgrades.map((upgrade) => <article key={upgrade.id}><span>{upgrade.category} · {upgrade.installDate ? dateLabel(upgrade.installDate) : "Install date pending"}</span><h3>{upgrade.name}</h3><p>{upgrade.description}</p>{upgrade.warranty ? <small>Warranty: {upgrade.warranty}</small> : null}</article>)}</div> : <p className="empty-state">No SmashPro-installed upgrades have been published.</p>}
      <div className="ledger-heading"><p className="eyebrow">Permanent upgrade ledger</p><h2>Nothing disappears.</h2></div><div className="upgrade-ledger" role="table" aria-label="Permanent upgrade ledger"><div className="ledger-row ledger-head" role="row"><span>Date</span><span>Upgrade</span><span>Cost</span><span>Value added</span><span>Video</span></div>{installedUpgrades.length ? installedUpgrades.map((upgrade) => <div className="ledger-row" role="row" key={upgrade.id}><span>{upgrade.installDate ? dateLabel(upgrade.installDate) : "Pending"}</span><strong>{upgrade.name}</strong><span>Private</span><span>{upgrade.estimatedAddedValue ? `+${new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(upgrade.estimatedAddedValue)}` : "Pending"}</span><span>{upgrade.youtubeUrl ? <a href={upgrade.youtubeUrl} aria-label={`${upgrade.name} video`}>View</a> : "—"}</span></div>) : <p className="empty-state">The immutable installed-upgrade ledger has no published entries yet.</p>}</div>
      <div className="wishlist-heading"><p className="eyebrow">Upgrade wishlist</p><h2>Next chapters.</h2></div>{plannedUpgrades.length ? <div className="wishlist-grid">{plannedUpgrades.map((upgrade) => <article key={upgrade.id}><span>{upgrade.status.replace("-", " ")}</span><h3>{upgrade.name}</h3><p>{upgrade.description}</p></article>)}</div> : <p className="empty-state">No planned upgrades are currently published.</p>}
      <div className="package-heading"><p className="eyebrow">Current packages</p><h2>Calculated from installed equipment.</h2></div>{packages.length ? <div className="package-grid">{packages.map((pack) => <article key={pack.id}><span>Qualified</span><h3>{pack.name}</h3><p>{pack.description}</p></article>)}</div> : <p className="empty-state">No package rule is currently satisfied. Packages are never manually assigned.</p>}
    </div></section>

    <section className="section shell passport-section"><div className="section-heading"><div><p className="eyebrow">Attachments</p><h2>Capability by configuration.</h2></div><p>Installed, available, and planned attachments remain distinct throughout the asset lifecycle.</p></div><div className="passport-card-grid">{item.attachments.map((attachment) => <article key={attachment.id}><span>{attachment.status}</span><h3>{attachment.name}</h3><p>{attachment.category}{attachment.description ? ` · ${attachment.description}` : ""}</p></article>)}</div>{item.includedItems.length ? <div className="included-items"><p className="eyebrow">Included accessories and spare parts</p><ul>{item.includedItems.map((item) => <li key={item.id}>{item.name}</li>)}</ul></div> : null}</section>

    <section className="metrics-section"><div className="shell ownership-metrics">{[["Days in Fleet", metrics.daysInFleet ?? "Pending"], ["Operating Hours", metrics.operatingHours ?? "Pending"], ["Attachments", metrics.totalAttachments], ["Installed Upgrades", metrics.totalUpgrades], ["Videos", metrics.totalVideos], ["Service Events", metrics.totalServiceEvents]].map(([label, value]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div></section>

    <section className="timeline-section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Equipment timeline</p><h2>One machine. One continuous record.</h2></div><p>Factory, ownership, maintenance, media, attachment, rental, and status events share a chronological ledger.</p></div><ol className="passport-timeline">{timeline.map((event) => <li key={event.id} className={event.milestone ? "is-milestone" : undefined}><time>{dateLabel(event.occurredAt)}</time><div><span>{event.milestone ? `Milestone · ${event.milestone.replaceAll("-", " ")}` : event.kind.replace("-", " ")}</span><h3>{event.title}</h3>{event.detail ? <p>{event.detail}</p> : null}</div></li>)}</ol></div></section>

    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Media history</p><h2>Documented from the source.</h2></div><p>Build photographs and videos stay attached to the equipment record, not a temporary campaign.</p></div><div className="gallery">{item.gallery.map((media) => <figure key={media.src}>{media.kind === "video" ? <video controls preload="metadata" aria-label={media.alt}><source src={media.src} type="video/mp4" /></video> : <img src={media.src} alt={media.alt} loading="lazy" width="900" height="1100" />}<figcaption>{media.caption}</figcaption></figure>)}</div></section>

    <section className="youtube-hub"><div className="shell"><div className="section-heading"><div><p className="eyebrow">SmashPro Garage</p><h2>Every episode. One machine.</h2></div><p>Installation, walkaround, review, maintenance, and Shorts records can link directly to the upgrade that created them.</p></div>{item.media.filter(({ kind }) => kind === "youtube").length ? <div className="youtube-grid">{item.media.filter(({ kind }) => kind === "youtube").map((media) => <a href={media.url} key={media.id}><span>{media.role ?? "episode"}</span><h3>{media.title}</h3><p>{media.description}</p></a>)}</div> : <p className="empty-state">No YouTube episodes have been published for this passport yet.</p>}</div></section>

    <section className="downloads-section"><div className="shell"><div><p className="eyebrow">Downloads & related episodes</p><h2>Documents that travel with the asset.</h2></div><CanonicalPublicDocuments assetCode={item.fleetId} />{downloads.length ? <div className="download-list">{downloads.map((document) => <a key={document.id} href={document.url}>{document.title}<span>{document.kind}</span></a>)}</div> : <p className="empty-state">No public manuals, brochures, or specification sheets are currently attached.</p>}{item.media.filter(({ kind }) => kind === "youtube").map((media) => <a className="youtube-link" key={media.id} href={media.url}>{media.title} →</a>)}</div></section>

    <section className="safety-section"><div className="shell two-columns"><div><p className="eyebrow">Safety and access</p><h2>Readiness before operation.</h2>{item.restrictions.map((value) => <p key={value}>{value}</p>)}</div><div className="requirements">{item.requirements.map((requirement) => <article key={requirement.title}><h3>{requirement.title}</h3><p>{requirement.detail}</p></article>)}</div></div></section>
    <section className="related shell"><div><p className="eyebrow">Related equipment passport</p><h2>{related.fleetId}</h2><p>{related.capabilityStatement}</p></div><Link className="related-image" to={related.publicPath}><img src={related.heroImage} alt={related.fleetId} width="1536" height="1024" loading="lazy" /><span>Open passport →</span></Link></section>
  </PageFrame>;
}
