import { Link } from "react-router-dom";
import { equipment } from "../data/equipment";
import { calculateOwnershipMetrics, calculatePackages, calculatePassportScores, generateBuildStory, publicTimeline } from "../domain/passport";
import { ButtonLink } from "../components/ButtonLink";
import { PageFrame } from "../components/PageFrame";
import { SeoSchema } from "../components/SeoSchema";
import { WindowSticker } from "../components/WindowSticker";
import { EquipmentProjects } from "../components/EquipmentProjects";
import { CanonicalPublicDocuments } from "../components/CanonicalPublicDocuments";

const dateLabel = (value?: string) => value ? new Intl.DateTimeFormat("en-US", { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)) : "Date documented privately";
const detailParagraphs = (detail: string) => detail.split("\n").map((line) => <p key={line}>{line}</p>);
const gallerySections = [
  ["factory", "Factory"],
  ["assembly", "Assembly"],
  ["branding", "Branding"],
  ["hydraulics", "Hydraulics"],
  ["completed-machine", "Completed Machine"],
  ["export", "Export"],
  ["shipping", "Shipping"],
  ["arrival", "Arrival"],
  ["commissioning", "Commissioning"],
] as const;

export function EquipmentDetailPage({ slug }: { slug: string }) {
  const item = equipment.find((entry) => entry.slug === slug)!;
  const related = equipment.find((entry) => entry.slug !== slug)!;
  const packages = calculatePackages(item.upgrades, item.packageRules);
  const scores = calculatePassportScores(item);
  const timeline = publicTimeline(item);
  const metrics = calculateOwnershipMetrics(item);
  const buildStory = generateBuildStory(item, packages);
  const publicOptions = item.factoryOptions.filter(({ publicDisplay }) => publicDisplay);
  const galleryById = new Map(item.gallery.flatMap((media) => media.id ? [[media.id, media] as const] : []));
  const installedUpgrades = item.upgrades.filter(({ status }) => status === "installed");
  const plannedUpgrades = item.upgrades.filter(({ status }) => status !== "installed" && status !== "removed");
  const downloads = item.documents.filter(({ publicDisplay, url }) => publicDisplay && url);
  const groupedGallery = gallerySections.map(([id, label]) => ({ id, label, items: item.gallery.filter(({ group }) => group === id) }));
  const ungroupedGallery = item.gallery.filter(({ group }) => !group);
  const isMzigoElectric = item.slug === "sp-mzigo-26";

  return <PageFrame><SeoSchema item={item} />
    <nav className="shell breadcrumbs" aria-label="Breadcrumb"><Link to="/">Equipment</Link><span>/</span><span aria-current="page">Passport {item.fleetId}</span></nav>
    <section className={`detail-hero passport-hero${isMzigoElectric ? " detail-hero--electric" : ""}`}><img src={item.heroImage} alt={`${item.fleetId} ${item.category}`} width="1536" height="1024" /><div className="detail-hero__shade" /><div className="ambient-light" aria-hidden="true" /><div className="shell detail-hero__content"><p className="eyebrow">SmashPro Fleet Equipment Passport</p><h1>{item.fleetId}</h1><p className="detail-name">Factory Model: {item.identity.factoryModel ?? "Not published"}</p><p className="detail-slogan">{item.slogan}</p><div className="button-row"><ButtonLink href="#identity">Open Passport</ButtonLink><ButtonLink href="#specifications" variant="outline">Factory Specifications</ButtonLink></div></div></section>

    {item.factoryUpdate ? <section className="factory-update" aria-labelledby="factory-update-heading"><div className="shell"><div className="factory-update__intro"><div><p className="eyebrow">Latest Factory Update · {dateLabel(item.factoryUpdate.date)}</p><h2 id="factory-update-heading">{item.factoryUpdate.heading}</h2></div><div>{item.factoryUpdate.description.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div><div className="factory-update__gallery">{item.factoryUpdate.images.map((media) => <figure key={media.src}><a href={media.src} target="_blank" rel="noopener noreferrer" aria-label={`Enlarge image: ${media.alt}`}><img src={media.src} alt={media.alt} loading="lazy" decoding="async" width={media.width} height={media.height} /></a><figcaption>{media.caption}<span>Click to enlarge</span></figcaption></figure>)}</div><div className="factory-update__lower"><figure className="factory-update__video"><video controls preload="metadata" poster={item.factoryUpdate.video.poster} aria-label={item.factoryUpdate.video.alt} width={item.factoryUpdate.video.width} height={item.factoryUpdate.video.height}><source src={item.factoryUpdate.video.src} type="video/mp4" /></video><figcaption>{item.factoryUpdate.video.caption}</figcaption></figure><div className="factory-update__timeline"><p className="eyebrow">Manufacturing Timeline</p><ol>{item.factoryUpdate.timeline.map((step) => <li className={`is-${step.status}`} key={step.label}><span aria-hidden="true">{step.status === "completed" ? "✓" : step.status === "current" ? "●" : "□"}</span><strong>{step.label}</strong><small>{step.status}</small></li>)}</ol></div></div></div></section> : null}

    {item.factoryUpdate ? <section className="factory-update" aria-labelledby="factory-update-heading"><div className="shell"><div className="factory-update__intro"><div><p className="eyebrow">Latest Factory Update · {dateLabel(item.factoryUpdate.date)}</p><h2 id="factory-update-heading">{item.factoryUpdate.heading}</h2></div><div>{item.factoryUpdate.description.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div><div className="factory-update__gallery">{item.factoryUpdate.images.map((media) => <figure key={media.src}><a href={media.src} target="_blank" rel="noopener noreferrer" aria-label={`Enlarge image: ${media.alt}`}><img src={media.src} alt={media.alt} loading="lazy" decoding="async" width={media.width} height={media.height} /></a><figcaption>{media.caption}<span>Click to enlarge</span></figcaption></figure>)}</div><div className="factory-update__lower"><figure className="factory-update__video"><video controls preload="metadata" aria-label={item.factoryUpdate.video.alt} width={item.factoryUpdate.video.width} height={item.factoryUpdate.video.height}><source src={item.factoryUpdate.video.src} type="video/mp4" /></video><figcaption>{item.factoryUpdate.video.caption}</figcaption></figure><div className="factory-update__timeline"><p className="eyebrow">Manufacturing Timeline</p><ol>{item.factoryUpdate.timeline.map((step) => <li className={`is-${step.status}`} key={step.label}><span aria-hidden="true">{step.status === "completed" ? "✓" : step.status === "current" ? "●" : "□"}</span><strong>{step.label}</strong><small>{step.status}</small></li>)}</ol></div></div></div></section> : null}

    <section className="passport-strip" id="identity"><div className="shell passport-identity">
      <div><span>Fleet Name</span><strong>{item.fleetId}</strong></div><div><span>Factory Model</span><strong>{item.identity.factoryModel ?? "Not published"}</strong></div><div><span>Manufacturer</span><strong>{item.specifications.find((spec) => spec.label === "Manufacturer")?.value ?? "Not published"}</strong></div><div><span>Passport ID</span><strong>{item.identity.passportId}</strong></div>
      {item.passportExplanation ? <div className="passport-identity__note"><span>Identity protocol</span><strong>{item.passportExplanation}</strong></div> : null}
    </div></section>

    <WindowSticker item={item} packages={packages} scores={scores} />

    <EquipmentProjects fleetId={item.fleetId} equipmentName={item.name} capabilityIds={item.capabilityIds} attachmentIds={item.attachmentIds} />

    <section className="build-story"><div className="shell"><p className="eyebrow">Build story</p><blockquote>{buildStory}</blockquote><p>This narrative evolves from verified factory, upgrade, package, and media records.</p></div></section>

    <section className="section shell passport-overview"><div><p className="eyebrow">Equipment identity</p><h2>A living record of the machine.</h2><p className="large-copy">{item.overview}</p><div className="status-panel"><span className="status-light" /><div><small>Current public status</small><strong>{item.statusLabel}</strong>{item.statusDetail ? <p>{item.statusDetail}</p> : null}</div></div></div><div className="passport-scores">
      <article><span>Documentation Score</span><strong>{scores.documentation}</strong><small>/ 100</small></article><article><span>Maintenance Score</span><strong>{scores.maintenance}</strong><small>/ 100</small></article><article className="valuation"><span>Estimated Fleet Value</span><strong>{item.valuation.status === "current" && item.valuation.amount ? new Intl.NumberFormat("en-US", { style: "currency", currency: item.valuation.currency, maximumFractionDigits: 0 }).format(item.valuation.amount) : "Pending"}</strong><small>{item.valuation.status === "current" ? "Public estimate" : "Awaiting verified valuation inputs"}</small></article>
    </div></section>

    {item.shippingStatus ? <section className="section shell logistics-dashboard" aria-labelledby="shipping-status-heading"><article className="current-location-card"><p className="eyebrow">Current Status</p><h2 id="shipping-status-heading">Where is {item.fleetId}?</h2><dl><div><dt>Current Status</dt><dd><span className="live-dot" />{item.shippingStatus.status}</dd></div><div><dt>Current Vessel</dt><dd>{item.shippingStatus.vessel}</dd></div><div><dt>Voyage</dt><dd>{item.shippingStatus.voyage}</dd></div><div><dt>Next Milestone</dt><dd>{item.shippingStatus.nextMilestone}</dd></div><div><dt>Estimated Arrival</dt><dd>{item.shippingStatus.estimatedArrival}</dd></div>{item.shippingStatus.trackingReference ? <div><dt>Tracking Reference</dt><dd>{item.shippingStatus.trackingReference}</dd></div> : null}</dl></article>{item.fleetStats?.length ? <div className="fleet-stat-grid">{item.fleetStats.map((stat) => <article key={stat.label}><span>{stat.label}</span><strong>{stat.value}</strong>{stat.detail ? <small>{stat.detail}</small> : null}</article>)}</div> : null}</section> : null}

    {item.shippingRoute?.length ? <section className="shipping-journey" aria-labelledby="shipping-journey-heading"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Shipping Journey</p><h2 id="shipping-journey-heading">Approximate logistics path.</h2></div><p>This decorative route shows the international movement only. Exact factory, warehouse, yard, and private destination locations are intentionally not published.</p></div><ol className="shipping-route">{item.shippingRoute.map((step, index) => <li className={`is-${step.status}`} key={step.label}><span>{index + 1}</span><strong>{step.label}</strong><small>{step.status}</small></li>)}</ol></div></section> : null}

    {item.lifecycleMilestones?.length ? <section className="section shell lifecycle-section" aria-labelledby="journey-milestones-heading"><div className="section-heading"><div><p className="eyebrow">Journey Milestones</p><h2 id="journey-milestones-heading">Built for future records.</h2></div><p>Each placeholder can receive a date, photos, videos, and notes as the machine moves from ocean freight to work history.</p></div><div className="lifecycle-grid">{item.lifecycleMilestones.map((milestone) => <article key={milestone.id} className={`is-${milestone.status}`}><span>{milestone.status}</span><h3>{milestone.label}</h3><dl><div><dt>Date</dt><dd>{milestone.date ? dateLabel(milestone.date) : "Pending"}</dd></div><div><dt>Photos</dt><dd>{milestone.photos.length}</dd></div><div><dt>Videos</dt><dd>{milestone.videos.length}</dd></div><div><dt>Notes</dt><dd>{milestone.notes ?? "Ready"}</dd></div></dl></article>)}</div></section> : null}

    <section className="spec-section" id="specifications"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Factory configuration</p><h2>Complete factory specifications.</h2></div><p>Every confirmed manufacturer value is shown. Fields are additive, so future OEM specifications can be published without redesigning the passport.</p></div><dl className="spec-grid passport-spec-grid">{item.specifications.map((spec) => <div key={spec.label}><dt>{spec.group}<small>{spec.label}</small></dt><dd>{spec.value}</dd></div>)}</dl>{item.factoryFinish ? <div className="factory-finish"><div className="factory-finish__heading"><div><p className="eyebrow">Official manufacturing information</p><h3>Factory Finish</h3></div></div><dl className="spec-grid factory-finish__grid"><div><dt>Paint Color</dt><dd>{item.factoryFinish.paintColor}</dd></div><div><dt>Color Standard</dt><dd>{item.factoryFinish.colorStandard}</dd></div><div><dt>Coating Process</dt><dd>{item.factoryFinish.coatingProcess}</dd></div><div><dt>Factory Cure</dt><dd>{item.factoryFinish.factoryCure}</dd></div></dl><aside className="factory-finish__callout"><span>RAL 6018</span><p>{item.factoryFinish.summary}</p></aside></div> : null}</div></section>

    <section className="section shell passport-section"><div className="section-heading"><div><p className="eyebrow">Factory options</p><h2>Installed before delivery.</h2></div><p>Only options approved for public display appear here. Factory costs remain in the private purchase ledger.</p></div>{publicOptions.length ? <div className="passport-card-grid factory-options-grid">{publicOptions.map((option) => { const evidence = option.evidenceMediaId ? galleryById.get(option.evidenceMediaId) : undefined; const imageEvidence = evidence?.kind !== "video" ? evidence : undefined; return <article className="factory-option-card" key={option.id}>{imageEvidence ? <a className="factory-option-card__evidence" href={`#media-${imageEvidence.id}`} aria-label={`View gallery evidence for ${option.name}: ${imageEvidence.alt}`}><img src={imageEvidence.src} alt={imageEvidence.alt} loading="lazy" decoding="async" width="800" height="500" style={{ objectPosition: option.evidenceObjectPosition }} /></a> : null}<div className="factory-option-card__body"><span>Factory installed</span><h3>{option.name}</h3><p>{option.description}</p>{imageEvidence ? <small>Factory build evidence · Aug 2026</small> : null}</div></article>; })}</div> : <p className="empty-state">No factory options have been published for this asset.</p>}</section>

    <section className="passport-dark"><div className="section shell passport-section"><div className="section-heading"><div><p className="eyebrow">SmashPro installed upgrades</p><h2>Built beyond factory.</h2></div><p>Install records can link vendors, warranties, images, receipts, and episodes. Financial documents remain private.</p></div>{installedUpgrades.length ? <div className="passport-card-grid">{installedUpgrades.map((upgrade) => <article key={upgrade.id}><span>{upgrade.category} · {upgrade.installDate ? dateLabel(upgrade.installDate) : "Install date pending"}</span><h3>{upgrade.name}</h3><p>{upgrade.description}</p>{upgrade.warranty ? <small>Warranty: {upgrade.warranty}</small> : null}</article>)}</div> : <p className="empty-state">No SmashPro-installed upgrades have been published.</p>}
      <div className="ledger-heading"><p className="eyebrow">Permanent upgrade ledger</p><h2>Nothing disappears.</h2></div><div className="upgrade-ledger" role="table" aria-label="Permanent upgrade ledger"><div className="ledger-row ledger-head" role="row"><span>Date</span><span>Upgrade</span><span>Cost</span><span>Value added</span><span>Video</span></div>{installedUpgrades.length ? installedUpgrades.map((upgrade) => <div className="ledger-row" role="row" key={upgrade.id}><span>{upgrade.installDate ? dateLabel(upgrade.installDate) : "Pending"}</span><strong>{upgrade.name}</strong><span>Private</span><span>{upgrade.estimatedAddedValue ? `+${new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(upgrade.estimatedAddedValue)}` : "Pending"}</span><span>{upgrade.youtubeUrl ? <a href={upgrade.youtubeUrl} aria-label={`${upgrade.name} video`}>View</a> : "—"}</span></div>) : <p className="empty-state">The immutable installed-upgrade ledger has no published entries yet.</p>}</div>
      <div className="wishlist-heading"><p className="eyebrow">Upgrade wishlist</p><h2>Next chapters.</h2></div>{plannedUpgrades.length ? <div className="wishlist-grid">{plannedUpgrades.map((upgrade) => <article key={upgrade.id}><span>{upgrade.status.replace("-", " ")}</span><h3>{upgrade.name}</h3><p>{upgrade.description}</p></article>)}</div> : <p className="empty-state">No planned upgrades are currently published.</p>}
      <div className="package-heading"><p className="eyebrow">Current packages</p><h2>Calculated from installed equipment.</h2></div>{packages.length ? <div className="package-grid">{packages.map((pack) => <article key={pack.id}><span>Qualified</span><h3>{pack.name}</h3><p>{pack.description}</p></article>)}</div> : <p className="empty-state">No package rule is currently satisfied. Packages are never manually assigned.</p>}
    </div></section>

    <section className="section shell passport-section"><div className="section-heading"><div><p className="eyebrow">Attachments</p><h2>Capability by configuration.</h2></div><p>Installed, available, and planned attachments remain distinct throughout the asset lifecycle.</p></div><div className="passport-card-grid">{item.attachments.map((attachment) => <article key={attachment.id}><span>{attachment.status}</span><h3>{attachment.name}</h3><p>{attachment.category}{attachment.description ? ` · ${attachment.description}` : ""}</p></article>)}</div>{item.includedItems.length ? <div className="included-items"><p className="eyebrow">Included accessories and spare parts</p><ul>{item.includedItems.map((item) => <li key={item.id}>{item.name}</li>)}</ul></div> : null}</section>

    <section className="metrics-section"><div className="shell ownership-metrics">{[["Days in Fleet", metrics.daysInFleet ?? "Pending"], ["Operating Hours", metrics.operatingHours ?? "Pending"], ["Attachments", metrics.totalAttachments], ["Installed Upgrades", metrics.totalUpgrades], ["Videos", metrics.totalVideos], ["Service Events", metrics.totalServiceEvents]].map(([label, value]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div></section>

    <section className="timeline-section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Equipment timeline</p><h2>One machine. One continuous record.</h2></div><p>Factory, ownership, maintenance, media, attachment, rental, and status events share a chronological ledger.</p></div><ol className="passport-timeline">{timeline.map((event) => <li key={event.id} className={event.milestone ? "is-milestone" : undefined}><time>{dateLabel(event.occurredAt)}</time><div><span>{event.milestone ? `Milestone · ${event.milestone.replaceAll("-", " ")}` : event.kind.replace("-", " ")}</span><h3>{event.title}</h3>{event.detail ? detailParagraphs(event.detail) : null}</div></li>)}</ol></div></section>

    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Media history</p><h2>Documented from the source.</h2></div><p>Build photographs and videos stay attached to the equipment record, not a temporary campaign.</p></div>{groupedGallery.map((group) => <div className={`gallery-group gallery-group--${group.id}`} key={group.id}><div className="gallery-group__heading"><p className="eyebrow">{group.label}</p><h3>{group.label}</h3></div>{group.items.length ? <div className={`gallery gallery--${group.id}`}>{group.items.map((media) => <figure id={media.id ? `media-${media.id}` : undefined} key={media.src}>{media.kind === "video" ? <video controls preload="metadata" aria-label={media.alt}><source src={media.src} type="video/mp4" /></video> : <img src={media.src} alt={media.alt} loading="lazy" decoding="async" width={media.width ?? 900} height={media.height ?? 1100} />}<figcaption>{media.caption}</figcaption></figure>)}</div> : <p className="empty-state">No {group.label.toLowerCase()} media has been published yet.</p>}</div>)}{ungroupedGallery.length ? <div className="gallery-group"><div className="gallery-group__heading"><p className="eyebrow">Build archive</p><h3>Additional Media</h3></div><div className="gallery">{ungroupedGallery.map((media) => <figure id={media.id ? `media-${media.id}` : undefined} key={media.src}>{media.kind === "video" ? <video controls preload="metadata" aria-label={media.alt}><source src={media.src} type="video/mp4" /></video> : <img src={media.src} alt={media.alt} loading="lazy" decoding="async" width={media.width ?? 900} height={media.height ?? 1100} />}<figcaption>{media.caption}</figcaption></figure>)}</div></div> : null}</section>

    <section className="youtube-hub"><div className="shell"><div className="section-heading"><div><p className="eyebrow">SmashPro Garage</p><h2>Every episode. One machine.</h2></div><p>Installation, walkaround, review, maintenance, and Shorts records can link directly to the upgrade that created them.</p></div>{item.media.filter(({ kind }) => kind === "youtube").length ? <div className="youtube-grid">{item.media.filter(({ kind }) => kind === "youtube").map((media) => <a href={media.url} key={media.id}><span>{media.role ?? "episode"}</span><h3>{media.title}</h3><p>{media.description}</p></a>)}</div> : <p className="empty-state">No YouTube episodes have been published for this passport yet.</p>}</div></section>

    <section className="downloads-section"><div className="shell"><div><p className="eyebrow">Downloads & related episodes</p><h2>Documents that travel with the asset.</h2></div><CanonicalPublicDocuments assetCode={item.fleetId} />{downloads.length ? <div className="public-document-list">{downloads.map((document) => <article className="public-document-card" key={document.id}><div className="public-document-card__icon" aria-hidden="true">PDF</div><div><span>Manufacturer document</span><h3>{document.title}</h3>{document.description ? <p>{document.description}</p> : null}<small>{document.kind.replace("-", " ")} · {document.source ?? "Public document"}</small></div><div className="public-document-card__actions"><a href={document.url} target="_blank" rel="noopener noreferrer" aria-label={`View ${document.title} PDF`}>View PDF</a><a href={document.url} download={document.downloadName} aria-label={`Download ${document.title} PDF`}>Download PDF</a></div></article>)}</div> : <p className="empty-state">No public manuals, brochures, or specification sheets are currently attached.</p>}{item.media.filter(({ kind }) => kind === "youtube").map((media) => <a className="youtube-link" key={media.id} href={media.url}>{media.title} →</a>)}</div></section>

    <section className="safety-section"><div className="shell two-columns"><div><p className="eyebrow">Safety and access</p><h2>Readiness before operation.</h2>{item.restrictions.map((value) => <p key={value}>{value}</p>)}</div><div className="requirements">{item.requirements.map((requirement) => <article key={requirement.title}><h3>{requirement.title}</h3><p>{requirement.detail}</p></article>)}</div></div></section>
    <section className="related shell"><div><p className="eyebrow">Related equipment passport</p><h2>{related.fleetId}</h2><p>{related.capabilityStatement}</p></div><Link className="related-image" to={related.publicPath}><img src={related.heroImage} alt={related.fleetId} width="1536" height="1024" loading="lazy" /><span>Open passport →</span></Link></section>
  </PageFrame>;
}
