import { Link } from "react-router-dom";
import { FleetLifecycleProgress } from "../components/FleetLifecycleProgress";
import { PageFrame } from "../components/PageFrame";
import { PassportDocumentRecord } from "../components/PassportDocumentRecord";
import { PassportEvidenceRecord } from "../components/PassportEvidenceRecord";
import { PassportHero } from "../components/PassportHero";
import { SeoSchema } from "../components/SeoSchema";
import { liftmateCaseStudyUrl, liftmateConfiguration, liftmateEquipment as item, liftmateFieldTests, liftmateLifecycle } from "../data/liftmateEquipment";

const nav = [
  ["Overview", "overview"], ["Identity", "identity"], ["SmashPro Edition", "smashpro-edition"], ["Partnership", "partnership"], ["Build Journey", "journey"],
  ["Specifications", "specifications"], ["Field Tests", "field-tests"], ["Media", "media"], ["Documents", "documents"], ["History", "history"],
] as const;
const groups = ["Identity", "Power", "Capacity", "Dimensions", "Mobility", "SmashPro Configuration"];
const mediaDestinations = ["Factory media", "Shipping media", "Commissioning", "Field tests", "Long-term use"];
const documentDestinations = ["OEM documentation", "Custom-build specification", "Factory proof", "Electrical / accessory diagram", "Commissioning checklist", "Warranty documentation", "Field-validation records"];

export function LiftMatePassportPage() {
  return <PageFrame><SeoSchema item={item} /><div className="liftmate-passport">
    <nav className="shell breadcrumbs" aria-label="Breadcrumb"><Link to="/">Equipment</Link><span>/</span><span aria-current="page">Passport {item.fleetId}</span></nav>
    <PassportHero titleId="liftmate-title" image={item.heroImage} alt="Proposed SP-LIFTMATE-27 SmashPro Edition concept based on the Pairon Tools Glide200" width={1536} height={1024} className="liftmate-hero">
      <p className="eyebrow">SmashPro Equipment Passport Â· Concept media</p><h1 id="liftmate-title">SP-LIFTMATE-27</h1><p className="liftmate-hero__platform">Pairon Tools Glide200</p><p className="lead">Proposed SmashPro Edition</p>
      <div className="liftmate-hero__status"><span>{item.statusLabel}</span><p>{item.statusDetail}</p></div>
      <div className="ardhi-v2-hero__actions"><a href="#overview">Open Passport</a><a href="#journey">Build Journey</a><a href="#partnership">Partnership Story</a><a href="#field-tests">Field Tests</a></div>
      <small>Proposed configuration artwork. It is not factory, production, delivery or field evidence.</small>
    </PassportHero>
    <nav className="passport-rail liftmate-rail" aria-label="SP-LIFTMATE-27 Passport sections"><div className="shell"><strong>{item.fleetId}</strong>{nav.map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</div></nav>

    <section className="section shell liftmate-overview" id="overview" aria-labelledby="overview-title"><div className="section-heading"><div><p className="eyebrow">Current status</p><h2 id="overview-title">Planning is documented.<br />The machine is not built.</h2></div><p>{item.overview}</p></div>
      <div className="liftmate-current-state"><article className="is-current"><span>Current phase</span><strong>Custom build planning</strong><p>Proposal and configuration questions are documented for partner and factory review.</p></article><article><span>Commercial gate</span><strong>Not authorized</strong><p>No public evidence of a paid deposit or build authorization.</p></article><article><span>Production gate</span><strong>Not started</strong><p>No factory proof, production media or QC evidence has been received.</p></article><article><span>Operational gate</span><strong>Not commissioned</strong><p>No ownership, installation, vehicle fitment or field performance claim is made.</p></article></div>
    </section>

    <section className="section shell" id="identity" aria-labelledby="identity-title"><div className="section-heading"><div><p className="eyebrow">Equipment identity</p><h2 id="identity-title">One platform.<br />Two identities kept clear.</h2></div><p>The OEM platform remains Pairon's Glide200. SP-LIFTMATE-27 is SmashPro's reserved identity for the proposed edition and its future lifecycle record.</p></div>
      <dl className="liftmate-identity"><div className="liftmate-identity__oem"><a href="https://pairontools.com/products/lift-slide-cart" target="_blank" rel="noreferrer" aria-label="View the Pairon Tools Glide200 on Pairon's website"><img src="/equipment/images/sp-liftmate-27-pairon-glide200-oem-thumbnail.jpg" alt="Pairon Tools Glide200 OEM lifting platform in a warehouse" width="1200" height="1200" loading="lazy" /></a><div><dt>OEM platform</dt><dd>Pairon Tools Glide200</dd><small>Official Pairon product image | View OEM platform</small></div></div><div><dt>SmashPro identity</dt><dd>{item.fleetId}</dd></div><div><dt>Edition</dt><dd>{item.identity.edition}</dd></div><div><dt>Model year</dt><dd>{item.identity.modelYear}</dd></div><div><dt>Passport ID</dt><dd>{item.identity.passportId}</dd></div><div><dt>Evidence state</dt><dd>Proposal / planning</dd></div></dl>
    </section>

    <section className="section liftmate-edition" id="smashpro-edition" aria-labelledby="edition-title"><div className="shell"><div className="section-heading"><div><p className="eyebrow">SmashPro Edition</p><h2 id="edition-title">Design intent with visible gates.</h2></div><p>Every feature keeps its evidence state. Proposed ideas cannot silently become approved, installed or validated equipment.</p></div><div className="liftmate-configuration">{liftmateConfiguration.map(feature=><article key={feature.id}><span className={`liftmate-state is-${feature.state}`}>{feature.state.replace("-"," ")}</span><h3>{feature.title}</h3><p>{feature.detail}</p></article>)}</div><div className="liftmate-state-key" aria-label="Configuration evidence states">{["Proposed","Factory review","Approved","Installed","Validated"].map((state,index)=><span key={state} className={index<2?"is-active":""}>{state}</span>)}</div></div></section>

    <section className="section shell liftmate-partnership" id="partnership" aria-labelledby="partnership-title"><div><p className="eyebrow">Partnership story</p><h2 id="partnership-title">SmashPro Ã— Pairon Tools</h2><p><strong>OEM platform:</strong> Glide200</p><p><strong>Relationship state:</strong> Proposal-stage discussions and configuration planning.</p><p>The Equipment Passport is the permanent technical and lifecycle record. The case study follows the collaboration framework, proposed video program and future field story.</p><a className="liftmate-primary-link" href={liftmateCaseStudyUrl}>View Partnership Case Study <span aria-hidden="true">â†’</span></a></div><aside><span>Two connected chapters</span><strong>Story / editorial</strong><i aria-hidden="true">â†•</i><strong>Technical Passport / lifecycle</strong><small>No private commercial terms are published.</small></aside></section>

    <div id="journey"><FleetLifecycleProgress stages={liftmateLifecycle} metrics={[{id:"recorded",label:"Recorded public events",value:item.timeline.length},{id:"approved",label:"Approved modifications",value:0},{id:"validated",label:"Completed field tests",value:0}]} currentStage="Configuration planning" nextStage="Factory proof" eyebrow="Build journey" title="Evidence advances the machine." description="Only documented concept and identity milestones are complete. Every physical build, shipment and operating stage remains pending until supported by evidence." /></div>

    <section className="section shell" id="specifications" aria-labelledby="specifications-title"><div className="section-heading"><div><p className="eyebrow">Specifications</p><h2 id="specifications-title">Published platform facts.<br />Pending SmashPro configuration.</h2></div><p>OEM values are attributed to Pairon-published information. Load suitability still depends on geometry, center of gravity, lifting points, surface conditions and current operating guidance.</p></div><div className="liftmate-spec-groups">{groups.map(group=><article key={group}><h3>{group}</h3><dl>{item.specifications.filter(spec=>spec.group===group).map(spec=><div key={spec.label}><dt>{spec.label}</dt><dd>{spec.value}<small>{spec.confirmed?"Published / allocated":"Confirmation pending"}</small></dd></div>)}</dl></article>)}</div></section>

    <section className="section liftmate-tests" id="field-tests" aria-labelledby="tests-title"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Field validation program</p><h2 id="tests-title">Five planned chapters.<br />Zero completed tests.</h2></div><p>The program is a proposal framework. Vehicle compatibility, machine performance and workflow outcomes remain unvalidated.</p></div><div className="liftmate-test-grid">{liftmateFieldTests.map((test,index)=><article key={test.id}><span>{String(index+1).padStart(2,"0")}</span><small>{test.state}</small><h3>{test.title}</h3><p>{test.detail}</p></article>)}</div><div className="liftmate-boundary"><strong>Operating boundary</strong><ul>{item.restrictions.map(value=><li key={value}>{value}</li>)}</ul></div></div></section>

    <section className="section shell" id="media" aria-labelledby="media-title"><div className="section-heading"><div><p className="eyebrow">Media archive</p><h2 id="media-title">A destination for evidence.<br />No empty slot becomes proof.</h2></div><p>The approved header is concept media. Other chapters stay visibly pending until authentic records exist.</p></div><div className="liftmate-media-archive"><figure><img src={item.heroImage} alt="SP-LIFTMATE-27 proposed SmashPro Edition concept board" width="1536" height="1024" loading="lazy" /><figcaption><strong>Concept media Â· documented</strong><span>Proposed SmashPro Edition configuration; not a photograph of a completed machine.</span></figcaption></figure>{mediaDestinations.map(label=><article key={label}><span>Awaiting evidence</span><h3>{label}</h3><p>This chapter activates only when verified public media is received.</p></article>)}</div></section>

    <section className="section shell liftmate-documents" id="documents" aria-labelledby="documents-title"><div className="section-heading"><div><p className="eyebrow">Passport documents</p><h2 id="documents-title">The library starts with honest gaps.</h2></div><p>No OEM or factory-issued LiftMate documents are currently published in this Passport.</p></div><PassportDocumentRecord item={item} /><div className="liftmate-document-slots">{documentDestinations.map(title=><article key={title}><span>Pending public record</span><h3>{title}</h3><p>No downloadable file is published.</p></article>)}</div></section>

    <section className="timeline-section liftmate-history" id="history" aria-labelledby="history-title"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Permanent history</p><h2 id="history-title">Supported events, expandable records.</h2></div><p>Dates and claims appear only where the public record supports them.</p></div><div className="liftmate-evidence-list">{item.timeline.filter(event=>event.publicDisplay).map((event,index)=><PassportEvidenceRecord key={event.id} id={`history-${event.id}`} date={event.occurredAt??"Date not published"} phase="Planning" title={event.title} label="Documented Â· Open record" defaultOpen={index===0}><p>{event.detail}</p><dl><div><dt>Evidence state</dt><dd>Documented public record</dd></div><div><dt>Physical machine evidence</dt><dd>Not present</dd></div></dl></PassportEvidenceRecord>)}</div></div></section>
  </div></PageFrame>;
}
