import { useEffect, useState } from 'react';
import '../styles/ardhi-expo.css';
import type { Equipment } from '../types/equipment';
import { ardhiCanonicalUrl, ardhiExpoUrl, comingSoon, opportunities, partnerLifecycle, partnerSurfaces, partnershipUrl } from '../data/ardhiExpo';
export { ardhiCanonicalUrl } from '../data/ardhiExpo';
export default function ArdhiExpo({ item }: { item: Equipment }) {
  const [qr, setQr] = useState('');
  const [selected, setSelected] = useState<string>(opportunities[0].id);
  const opportunity = opportunities.find(entry => entry.id === selected) ?? opportunities[0];
  const partners = (item.partners ?? []).filter(partner => ['confirmed', 'active', 'completed'].includes(partner.status));
  useEffect(() => {
    let active = true;
    void import('qrcode').then(module => module.default.toDataURL(ardhiExpoUrl, { width: 320, margin: 4, errorCorrectionLevel: 'M' })).then(url => { if (active) setQr(url); }).catch(() => { /* The canonical link remains available. */ });
    return () => { active = false; };
  }, []);
  return <section className="shell sponsor-experience" id="expo-experience" aria-labelledby="expo-title">
    <header><p className="eyebrow">Equip Expo · An invitation to participate</p><h2 id="expo-title">What could your company become part of?</h2><p>Every sponsor, attachment, upgrade, maintenance event, mission and customer project can become part of this machine's permanent history, with reviewed evidence.</p><a className="sponsor-button" href="#expo-partnership">Become Part of the Journey</a></header>
    <div className="sponsor-intro-grid"><article className="sponsor-video"><p className="eyebrow">Mission Video · Coming soon</p><h3>From the factory to the work ahead.</h3><p>Factory → Shipment → Delivery → Startup → Jobs → Sponsors</p><p className="flagship-note">The mission film is planned. Explore the real factory evidence while its next chapters take shape.</p><a href="#history-production-complete">Explore the documented build</a></article><article><h3>Why Companies Partner</h3><p>This is not a one-time advertisement. A documented contribution becomes part of the machine's permanent digital identity.</p><details className="flagship-disclosure"><summary>Where your contribution can appear</summary><ul className="sponsor-surfaces">{partnerSurfaces.map(surface => <li key={surface}>{surface}</li>)}</ul><p className="flagship-note">Placement and publication are agreed per collaboration. Digital HQ records remain private where required.</p></details></article></div>
    <section id="expo-opportunities" aria-labelledby="opportunities-title"><h3 id="opportunities-title">Current Opportunities</h3><label className="sponsor-selector">Find your place in the story<select value={selected} onChange={event => setSelected(event.target.value)}>{opportunities.map(entry => <option key={entry.id} value={entry.id}>{entry.title} · {entry.status}</option>)}</select></label><article className="sponsor-opportunity" aria-live="polite"><span className="sponsor-status">{opportunity.status}</span><h4>{opportunity.title}</h4><p><strong>Future mission</strong><br />{opportunity.mission}</p><a href="#expo-partnership">Discuss {opportunity.title.toLowerCase()}</a></article><p className="flagship-note">Available means open for discussion, not a reserved placement. Pending is not an agreement. Installation, field results and coverage require evidence.</p></section>
    <details className="flagship-disclosure"><summary>What happens after you partner</summary><ol className="sponsor-lifecycle">{partnerLifecycle.map(step => <li key={step}>{step}</li>)}</ol><p>Products remain connected to their installation, use and follow-up. This is a proposed path, not a guarantee of publication, customer work or a positive review.</p></details>
    <details className="flagship-disclosure"><summary>Coming Soon · Six first chapters</summary><div className="sponsor-coming">{comingSoon.map(title => <article key={title}><h4>{title}</h4><p>Coming soon · Your contribution could help document this chapter.</p><a href="#expo-partnership">Explore participation</a></article>)}</div><p className="flagship-note">Delivery, commissioning, fitment and project approval come first. No customer jobs are confirmed here.</p></details>
    <details className="flagship-disclosure"><summary>Living partner records · Evidence before claims</summary><div className="sponsor-records">{partners.map(partner => <article key={partner.id}><p className="eyebrow">{partner.category} · {partner.status}</p><h3>{partner.brand}</h3><p>{partner.description}</p><dl><div><dt>Contribution</dt><dd>{partner.relationship}</dd></div><div><dt>Equipment installed</dt><dd>YF380 factory build; field installation not recorded</dd></div><div><dt>Date</dt><dd>See dated factory history</dd></div><div><dt>Videos</dt><dd><a href="#history-production-complete">Factory evidence archive</a></dd></div><div><dt>Mission count</dt><dd>Not recorded</dd></div><div><dt>Service hours</dt><dd>Not recorded · commissioning pending</dd></div><div><dt>Reviews</dt><dd>Field review pending</dd></div><div><dt>Status</dt><dd>Factory contribution documented; no new sponsorship asserted</dd></div></dl>{partner.storyUrl && <a href={partner.storyUrl}>Read the contribution record</a>}</article>)}</div></details>
    <section className="sponsor-cta" id="expo-partnership" aria-labelledby="partnership-title"><p className="eyebrow">Become Part of the Journey</p><h3 id="partnership-title">Your company can become part of what happens next.</h3><p>Interested manufacturers, suppliers and technology partners can become part of SP-ARDHI-26's permanent digital story. The aim is to document each collaboration from installation through years of real-world operation.</p><p className="sponsor-interest">Your interest: <strong>{opportunity.title}</strong> · Mention SP-ARDHI-26 and this opportunity in your message.</p><a className="sponsor-button" href={partnershipUrl}>Discuss Partnership</a><p className="flagship-note">Opens the existing SmashPro contact page. Partnership scope and documentation are agreed together.</p></section>
    <details className="flagship-disclosure"><summary>Share the Expo experience · QR</summary><div className="flagship-expo"><div><h3>One machine. One permanent identity.</h3><p>The Expo QR opens this same Passport with <code>?expo=true</code>.</p><a href={ardhiCanonicalUrl}>Open the SP-ARDHI-26 passport</a></div>{qr && <img src={qr} width="320" height="320" alt="Scan to open the SP-ARDHI-26 Expo experience" />}</div></details>
    <a className="sponsor-record-link" href="#passport">Continue into the permanent machine record ↓</a>
  </section>;
}
